<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Outline.Rag.Application\Outline.Rag.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Anthropic" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="OllamaSharp" />
    <PackageReference Include="Microsoft.ML.Tokenizers" />
    <PackageReference Include="Microsoft.ML.Tokenizers.Data.Cl100kBase" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" />
    <PackageReference Include="CommunityToolkit.VectorData.PgVector" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Outline.Rag.UnitTests" />
  </ItemGroup>
</Project>
